import {
  Injectable,
  Logger,
  OnModuleInit,
  ServiceUnavailableException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { PrismaService } from '../prisma/prisma.service';
import { CorsOriginsService } from './cors-origins.service';

@Injectable()
export class TraefikDomainsSyncService implements OnModuleInit {
  private readonly logger = new Logger(TraefikDomainsSyncService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
    private readonly corsOrigins: CorsOriginsService,
  ) {}

  async onModuleInit(): Promise<void> {
    try {
      await this.sync();
    } catch (error) {
      this.logger.warn(
        `Initial Traefik domain sync skipped: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }

  isConfigured(): boolean {
    return Boolean(this.dynamicDir());
  }

  async sync(): Promise<{ hosts: string[]; path: string | null }> {
    const dir = this.dynamicDir();
    if (!dir) {
      return { hosts: [], path: null };
    }

    const reserved = this.reservedHosts();
    const rows = await this.prisma.storeDomain.findMany({
      where: {
        isActive: true,
        host: { not: null },
        store: { isActive: true },
      },
      select: { host: true },
      orderBy: { host: 'asc' },
    });

    const hosts = [
      ...new Set(
        rows
          .map((row) => row.host?.trim().toLowerCase() ?? '')
          .filter((host) => host && !reserved.has(host)),
      ),
    ].sort();

    await mkdir(dir, { recursive: true });
    const filePath = join(dir, 'storefronts.yml');
    const contents = this.renderYaml(hosts);
    await writeFile(filePath, contents, 'utf8');

    await this.corsOrigins.refresh();

    this.logger.log(
      hosts.length === 0
        ? `Traefik storefronts.yml cleared (${filePath}).`
        : `Traefik storefronts.yml synced ${hosts.length} host(s) → ${filePath}`,
    );

    return { hosts, path: filePath };
  }

  async syncOrThrow(): Promise<{ hosts: string[]; path: string }> {
    const dir = this.dynamicDir();
    if (!dir) {
      throw new ServiceUnavailableException(
        'TRAEFIK_DYNAMIC_DIR is not set; cannot sync Traefik hosts.',
      );
    }
    const result = await this.sync();
    return { hosts: result.hosts, path: result.path ?? join(dir, 'storefronts.yml') };
  }

  private dynamicDir(): string | undefined {
    const dir = this.config.get<string>('TRAEFIK_DYNAMIC_DIR')?.trim();
    return dir || undefined;
  }

  private reservedHosts(): Set<string> {
    const values = [
      this.config.get<string>('WEB_DOMAIN'),
      this.config.get<string>('WEB_WWW_DOMAIN'),
      this.config.get<string>('ADMIN_DOMAIN'),
      this.config.get<string>('API_DOMAIN'),
      this.config.get<string>('POS_DOMAIN'),
      'marinapizzas.com.au',
      'www.marinapizzas.com.au',
      'admin.marinapizzas.com.au',
      'api.marinapizzas.com.au',
      'pos.marinapizzas.com.au',
    ];
    return new Set(
      values
        .map((value) => value?.trim().toLowerCase() ?? '')
        .filter(Boolean),
    );
  }

  private renderYaml(hosts: string[]): string {
    const header = [
      '# Generated by piza-api TraefikDomainsSyncService — do not edit by hand.',
      `# Updated: ${new Date().toISOString()}`,
      '# Routes custom StoreDomain hosts to the shared web container (piza-web@docker).',
      '',
    ].join('\n');

    if (hosts.length === 0) {
      return `${header}http: {}\n`;
    }

    const rule = hosts.map((host) => `Host(\`${host}\`)`).join(' || ');
    return `${header}http:
  routers:
    piza-storefronts:
      rule: "${rule}"
      entryPoints:
        - websecure
      service: piza-web@docker
      tls:
        certResolver: letsencrypt
`;
  }
}
